### ISSUE TITLE
when code will be released?

### ISSUE THREAD

**Issue by jiangzhengkai** [bharatsingh430/snip#4]

**Comment by xiaoyongzhu** [comment]
Also wondering about this..

**Comment by makefile** [comment]
> Code for SNIPER will be released in first week of June. The repo will also include R-FCN-3000 and SNIP.

**Comment by Angzz** [comment]
Hi, it's already June, so when will the code release??? I can't wait to have a try @makefile

**Comment by bharatsingh430** [comment]
We are merging different branches and cleaning up some code so that its easy to use. Training was done on servers which had  500GB of RAM and 64 cores, so in its current form, its resource hungry. We are fixing the code so that it can be run efficiently on normal workstations. It will be out very soon, like 3-4 days.

**Comment by jiangzhengkai** [comment]
it's already 16,june,why the code still don't release?

**Comment by bharatsingh430** [comment]
check this link by tomorrow night https://github.com/mahyarnajibi/SNIPER  (EST). Its taking more time than we expected as research code is hacky and needs a lot of cleanup, verification and testing before public release :( . But I can assure you, it is worth the wait and will possibly be the most efficient publicly available training code you can find for object detection / instance segmentation!

**Comment by revilokeb** [comment]
I am also looking forward to the release of the code in order to understand better and in in more detail their approach described in the publications. But I am seeing it rather as niceness of the authors that they are releasing their code at all and in addition go through the effort to make it usable for externals, very much appreciated. So of course take all the time to bring the code into a shape such that you like releasing it. Thank you in advance @bharatsingh430 !
